version: "3.9"
services:
  db:
    image: postgres:15
    container_name: librify_db
    restart: always
    environment:
      POSTGRES_USER: librify_user
      POSTGRES_PASSWORD: librify_password
      POSTGRES_DB: librify_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
